server:
  port: 9898
spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: XXXXXXXXXXXXXXXX
            client-secret: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX